import type { MetadataRoute } from 'next';
export const dynamic = 'force-static';
import {
  ROUTE_HOME,
  ROUTE_CONTACT,
  ROUTE_ENTREPRISE_BASE,
  ROUTE_PRESTATIONS_CARTOGRAPHIER,
  ROUTE_PRESTATIONS_AMELIORATION_CONTINUE,
  ROUTE_PRESTATIONS_IDENTIFIER_PROJETS,
  ROUTE_PRESTATIONS_VERIFIER_PERFORMANCE,
  ROUTE_PRESTATIONS_COORDONNER_ENERGIE_DIGITAL_PERFORMANCE,
  ROUTE_PRESTATIONS_CONFORMITE,
  ROUTE_APPROCHE_EXPERTISE_DATA,
  ROUTE_APPROCHE_MANAGEMENT_DONNEE,
  ROUTE_MENTIONS_LEGALES,
  ROUTE_POLITIQUE_CONFIDENTIALITE,
} from '@/constants/routes';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://colby-industries.fr';
  const paths = [
    ROUTE_HOME,
    ROUTE_ENTREPRISE_BASE,
    ROUTE_CONTACT,
    ROUTE_MENTIONS_LEGALES,
    ROUTE_POLITIQUE_CONFIDENTIALITE,
    ROUTE_APPROCHE_EXPERTISE_DATA,
    ROUTE_APPROCHE_MANAGEMENT_DONNEE,
    ROUTE_PRESTATIONS_CARTOGRAPHIER,
    ROUTE_PRESTATIONS_CONFORMITE,
    ROUTE_PRESTATIONS_AMELIORATION_CONTINUE,
    ROUTE_PRESTATIONS_IDENTIFIER_PROJETS,
    ROUTE_PRESTATIONS_VERIFIER_PERFORMANCE,
    ROUTE_PRESTATIONS_COORDONNER_ENERGIE_DIGITAL_PERFORMANCE,
  ];

  return paths.map((p) => ({ url: `${base}${p}`, lastModified: new Date() }));
}
